export const authConstants ={
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FALIURE: 'LOGIN_FALIURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED',
    SIGN_UP_REQUEST: 'SIGNUP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
}

export const generalConstatnts = {
    MODE_CHANGE_REQUEST: "MODE_CHANGE_REQUEST",
    SET_MODE_DARK: "SET_MODE_DARK",
    SET_MODE_LIGHT: 'SET_MODE_LIGHT'
}
export const revOrderConstants = {
    PLACE_ORDER_REQUEST: 'PLACE_ORDER_REQUEST',
    PLACE_ORDER_SUCCESS: 'PLACE_ORDER_SUCCESS',
    PLACE_ORDER_FAILURE: 'PLACE_ORDER_FAILURE',
    GET_ORDER_REQUEST: 'GET_ORDER_REQUEST',
    GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
    GET_ORDER_FAILURE: 'GET_ORDER_FAILURE',
}
export const acptOrderConstants = {
    ACPT_ORDER_REQUEST: 'ACPT_ORDER_REQUEST',
    ACPT_ORDER_SUCCESS: 'ACPT_ORDER_SUCCESS',
    ACPT_ORDER_FAILURE: 'ACPT_ORDER_FAILURE',
    GET_ACPT_ORDER_REQUEST: 'GET_ACPT_ORDER_REQUEST',
    GET_ACPT_ORDER_SUCCESS: 'GET_ACPT_ORDER_SUCCESS',
    GET_ACPT_ORDER_FAILURE: 'GET_ACPT_ORDER_FAILURE',
}
export const completeConstants = {
    COMPLETE_ORDER_REQUEST: 'COMPLETE_ORDER_REQUEST',
    COMPLETE_ORDER_SUCCESS: 'COMPLETE_ORDER_SUCCESS',
    COMPLETE_ORDER_FAILURE: 'COMPLETE_ORDER_FAILURE',
    GET_COMPLETE_ORDER_REQUEST: 'GET_COMPLETE_ORDER_REQUEST',
    GET_COMPLETE_ORDER_SUCCESS: 'GET_COMPLETE_ORDER_SUCCESS',
    GET_COMPLETE_ORDER_FAILURE: 'GET_COMPLETE_ORDER_FAILURE',
}